name: story_app
description: Story App from dicoding

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  injectable:
  get_it: ^7.2.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  equatable: ^2.0.5
  freezed: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: '>=4.0.0 <5.0.0'
  injectable_generator:
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true