name: story_app
description: Story App from dicoding

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: any
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  chopper: ^6.0.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  chopper_generator: ^6.0.0
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true