name: story_app
description: Story App from dicoding

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  chopper: ^6.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.17
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.4
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: any
  logging: ^1.1.1
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1
  hive_test: ^1.0.1
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
